### ISSUE TITLE
override css

### ISSUE THREAD

**Issue by GoNode5** [ng-select/ng-select#156]
Sorry if this is more a support question but I need to override the component css. What would be the best approach in combination with Bootstrap
I tried this...
```
   .ng-select  {
            border:0px;
            min-height: 0px;
            border-radius: 0;
        }
        .ng-control  {            
            min-height: 0px;
            border-radius: 0;
        }
        :host-context(.selectcustom) .ng-control {                    
            min-height: 0px;
            border-radius: 0;
        }
```

**Comment by varnastadeus** [comment]
I think best approach would be adding custom class on `ng-select` and then applying your css.
Try this:

```html
<ng-select class="custom"></ng-select>
```

```css
.ng-select.custom {
    border:0px;
    min-height: 0px;
    border-radius: 0;
    ....
}
```

**Comment by GoNode5** [comment]
@varnastadeus doesn't seem to have any effect...?

**Comment by varnastadeus** [comment]
@GoNode5  here is plnkr https://plnkr.co/edit/uEPHakayUX0IeKcyaxjL?p=preview

**Comment by GoNode5** [comment]
@varnastadeus ok had to add it to  angular-cli.json / style.css. Working now 
Thanks again for your help!!!

**Comment by marina-ferreira** [comment]
If you are using ViewEncapsulation, your should use special `::ng-deep` selector which will prevent scoping for nested selectors.

```css
.ng-select.custom ::ng-deep .ng-select-container  {            
    min-height: 0px;
    border-radius: 0;
}
```
https://www.npmjs.com/package/@ng-select/ng-select
