### ISSUE TITLE
ng-dropdown-panel width out of sync with input-container when appendTo="body" is passed

### ISSUE THREAD

**Issue by rohan-paul** [ng-select/ng-select#1643]
**Describe the bug**

My apology if its not really a bug or issue and I am only missing some implementation details here.

#### `ng-dropdown-panel` width is getting out of sync when `appendTo="body"` is passed to `ng-select`

From source-code, when `appendTo="body"` is set the dropdown styles seem to determinded by [below code in the ng-select packgae](https://github.com/ng-select/ng-select/blob/3d2479129f164546f1c434127ff46ff6e329bac7/src/ng-select/lib/ng-dropdown-panel.component.ts#L393)

```js
private _updatePosition() {
        const select = this._select.getBoundingClientRect();
        const parent = this._parent.getBoundingClientRect();
        const offsetLeft = select.left - parent.left;

        this._setOffset(parent, select);

        this._dropdown.style.left = offsetLeft + 'px';
        this._dropdown.style.width = select.width + 'px';
        this._dropdown.style.minWidth = select.width + 'px';
    }
```

**To Reproduce** 

I am using `ng-select` and have quite a bit of custom styles defined to it as below in a .scss file using `@mixin` as below

```css

@mixin custom-ng-select {
  @include custom-ng-select-ip();
  @include custom-text-body-light-2();

  caret-color: mat-color($sdk-secondary, 500);

  &.ng-select .ng-select-container {
    box-shadow: none;
    min-height: $custom-ng-select-height;
    display: flex;
    align-items: center;
  }

  &.ng-select.ng-select-single .ng-select-container {
    height: $custom-ng-select-height;
  }

 &.ng-select
    &.ng-dropdown-panel
    .ng-dropdown-panel-items
    .ng-option.ng-option-marked {
    padding-left: $custom-ng-select-pl;
    height: $custom-ng-select-height;
  }

...and many more styles...

```
And then in my Angular app's global `styles.scss` file getting this custom styles @mixin as below

```
.ng-select {
  @include custom-ng-select();
}
```

**And this is working fine as expected.**

But when I am rendering `<ng-select>` with `appendTo="body"` then the `ng-dropdown-panel` is no more taking the custom styles and the reason is as below per [ng-select official doc](https://github.com/ng-select/ng-select/blob/3018a1098ba2ad06fbdf4dfe60209087cbd68185/src/demo/app/examples/append-to-example/append-to-example.component.html)

`By default dropdown panel is rendered as child element of ng-select, but you can append dropdown to any element using appendTo`

That is in below case `ng-dropdown-panel` is no more a child of `ng-select` and not taking the styles that have been defined in my .scss file's `@mixin`

```
    <ng-select
      appendTo="body"
      [items]="items"
      [bindLabel]="'name'"      
    >
    </ng-select>
```

But in my case I want to retain the width exactly in sync between `ng-dropdown-panel` and `.ng-select-container` when I have `appendTo="body"` in my `ng-select` implementation.

#### Screenshot

Below screenshot is the top-most `ng-select` and this is how `ng-dropdown-panel`'s custom styles is getting broken when using with `appendTo="body"`

![image](https://user-images.githubusercontent.com/12703975/84124002-3fa76380-aa58-11ea-8f4d-4332ee0c8a3b.png)

And below screenshots where I have NOT used `appendTo="body"`

![image](https://user-images.githubusercontent.com/12703975/84132397-746ce800-aa63-11ea-8114-1331944fe478.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Chrome
