### ISSUE TITLE
Selected options goes blank in mobile.

### ISSUE THREAD

**Issue by vijay94** [ng-select/ng-select#1735]
When you type a matching string and select some value from the drop down. The selected option goes blank. But the field has value. This can be reproduced in offical examples also. Occurs only in mobile browser.

**Comment by vijay94** [comment]
@varnastadeus when you search and select any string from the dropdown. The value gets selected and formControl is validated. But the selected value is not visible. This is only happening in mobile devices. I noticed this issue in offical examples also. Please find the attachment(value gets selected).
![WhatsApp Image 2020-09-22 at 23 53 06](https://user-images.githubusercontent.com/8709375/93921886-cf82cc00-fd2e-11ea-99df-2c616472d62f.jpeg)

**Comment by arthurfrancioni** [comment]
Add this css

```
.ng-select.ng-select-single.ng-select-filtered {
  visibility: initial!important;
   /* or visibility: initial!important; */
}
```

**Comment by Betest** [comment]
> Add this css, solved the problem here.
> 
> ```
> .ng-select.ng-select-single.ng-select-filtered {
>   visibility: visible!important;
>    /* or visibility: initial!important; */
> }
> ```

don´t work :(

**Comment by vijay94** [comment]
.ng-select.ng-select-single.ng-select-filtered .ng-select-container .ng-value-container .ng-value {
    visibility: hidden;
}

seems to be the problem

**Comment by dosborne-dingo** [comment]
This seems to be because the `compositionend` event isn't fired until the user hides the onscreen keyboard or taps the enter/accept button in Android.

If the user just selects an option from the dropdown first and then hides the keyboard, the `compositionend` event isn't fired, and `NgSelectComponent._isComposing` isn't marked as false again.

**Comment by SublimePotato** [comment]
Seems to be a duplicate of #1642 - the fix is not merged yet, but the issue is closed. 
The implementation of composition events did cause a lot of issues and still is. If default solutions like Google Keyboard are not supporting it, maybe it is too soon to use it in code. 

This fixes it until the proper fix is merged.
```scss
// fixes blank value in select after filtering and selecting on mobile (until https://github.com/ng-select/ng-select/pull/1556 is merged)
::ng-deep{
  .ng-select.ng-select.ng-select-single.ng-select-filtered:not(.ng-select-opened) .ng-select-container.ng-has-value .ng-value-container .ng-value{
    visibility: visible;
  }
}
```
