### ISSUE TITLE
Fixed height for multi-select dropdown

### ISSUE THREAD

**Issue by drk-mtr** [ng-select/ng-select#1829]
Firstly, thanks for the brilliant component - it's really well designed and easy to use.

This issue is closed so apologies for adding another one: https://github.com/ng-select/ng-select/issues/979

The suggestion here seems to be that this should be straightforward to achieve, however I don't understand what's required. I would like the dropdown to stop expanding vertically at a certain threshold and show a scrollbar.

However, if I add a `max-height` to the `.ng-select-container` as follows, when I put a few items in the dropdown the items at the top are cut off.

```css
.ng-select .ng-select-container {
    max-height: 7.5rem;
    overflow-y: auto !important;
    overflow-x: hidden;
}
```

In the dropdown below, I am unable to scroll up any further:

![dropdown](https://user-images.githubusercontent.com/40315783/102786773-f1c0d000-4397-11eb-9af4-bc525ad60663.png)

Is it possible to achieve this with functionality built in to this library, or is it recommended that people find their own custom ways of achieving this?

EDIT: It appears I can get part way there by setting the bottom position as below. However when clicking the scrollbar this registers a mouseclick (opening the menu) which I wouldn't want, and the `x` does not stay visible. On reflection I should probably be asking these queries on stackoverflow, so please feel free to close the feature request if you don't feel it's appropriate for here.

```css
.ng-select .ng-select-container {
    max-height: 7.5rem;
    overflow-y: auto !important;
    overflow-x: hidden;
    position: relative;
    bottom: 0;
}
```
