### ISSUE TITLE
selected long text item stretches dropdown 

### ISSUE THREAD

**Issue by DecentCZ** [ng-select/ng-select#215]
### Expected behaviour
The dropdown should not stretch and and just apply ellipsis when long text gets selected

### Actual behaviour
dropdown stretches when selecting long text items messing up the page

### More Info
ng-select version: [0.12.0]

browser: [Google Chrome] Version 63.0.3239.132

reproducible in demo page: [NO]

**Comment by anjmao** [comment]
@DecentCZ Hi, do you mean in should apply ellipsis for dropdown items? You could apply style for `ng-option`

```css
.ng-option {
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}
```

This was left for consumer to decided because some may not want to add hidden overflow.
