### ISSUE TITLE
Behavior of the dropdown list when it contains long labels

### ISSUE THREAD

**Issue by Juuu23** [ng-select/ng-select#2518]
### Is your feature request related to a problem? Please describe

Congratulations and thank you for all the work you’ve done.

I have been working on displaying long labels in dropdown lists within my application. Partially using your ng-select component for the features it provides, I have noticed some differences compared to the display behavior of Angular Material's mat-select. Therefore, I was wondering if the following behaviors could eventually be implemented?

### Describe the solution you'd like

- Having the dropdown list adjust its width based on its content rather than the width of the dropdown field.
- Displaying the dropdown list below to the left or below to the right of the dropdown field, depending on where there is more space.
- Displaying dropdown list labels on multiple lines when they are still too long (an ellipsis could also be an alternative).

### Describe alternatives you've considered

I don't see anything else.

### Additional context

These behaviors are typically found in mat-select, as shown in the screenshots below.

![Image](https://github.com/user-attachments/assets/88646831-a7ff-4115-acbc-5b009ed2c222)

![Image](https://github.com/user-attachments/assets/46029ac5-3d73-496e-aa11-8eab59dd3c4c)

Do you plan to incorporate such display behaviors?

**Comment by pavankjadda** [comment]
Thanks for the report, but most of this is out of scope.

Dropdown width and label wrapping are styling concerns you can handle with your own CSS on `.ng-dropdown-panel` and `.ng-option` (for example a `min-width`, or `white-space: normal` to wrap). The "pick left or right based on available space" part is overlay-positioning behavior the component doesn't do, and it's closer to Angular Material/CDK territory.

Closing for now. If you think I got this wrong, drop a comment or open a fresh issue and I'll take another look.

**Comment by microspec-chris** [comment]
I used this CSS to allow each option in the drop-down list to wrap to multiple lines:
```css
/* Override option item styling for @ng-select/ng-select */
.ng-dropdown-panel .ng-dropdown-panel-items .ng-option {
  /* Rather than a single line possibly truncated, allow wrapping to multiple lines */
  white-space: normal !important;
}
```
