### ISSUE TITLE
Set uppercase in search input.

### ISSUE THREAD

**Issue by fernandoGN** [ng-select/ng-select#411]
I'm trying to use uppercase in the css of the search input, however it did not work ...

.ng-select.custom {
     text-transform: uppercase;
}
.ng-select.custom .ng-control {
     text-transform: uppercase;
}

How i can do this ?

**Comment by anjmao** [comment]
Hi @fernandoGN 
Please do not ask such general questions here, better create it on stackoverflow, because this is a question sounds like: How css works?

You need to style .ng-input.

```css
.ng-select.custom .ng-control .ng-input {
     text-transform: uppercase;
}
```
