### ISSUE TITLE
How I can update arrow icon?

### ISSUE THREAD

**Issue by abhishekgupta1991** [ng-select/ng-select#544]
I want to use arrow image or custom font icon rather than default one. How can I customize it?

**Comment by rankill** [comment]
You could do something like this 

`    ng-select .ng-select-container span.ng-arrow-wrapper span.ng-arrow {
      @include transition(transform, .5s, cubic-bezier(.4,.2,0,1));

      border-width: 0;
      background-color: $color-04;

      mask-image: url('assets/icons/arrow-down-icon.svg');
      mask-size: contain;

      -webkit-mask-image: url('assets/icons/arrow-down-icon.svg');
      -webkit-mask-size: contain;

      height: 24px;
      top: 3px;
      width: 24px;
    }`

Hope it helps

**Comment by abhishekgupta1991** [comment]
It is not working perfectly. Still trying to figure it out. Can we update the HTML??

**Comment by varnastadeus** [comment]
You can't change HTML and I don't see the need for it since the arrow itself is formed using css. Here is another way to achieve it:

Font-awesome: 
--
```css
.ng-select .ng-arrow-wrapper .ng-arrow {
    display: none;
}

.ng-select span.ng-arrow-wrapper:before {
    content: "\f0ab";
    display: inline-block;
    font: normal normal normal 14px/1 FontAwesome;
    font-size: inherit;
    text-rendering: auto;
}
```
<img width="695" alt="screen shot 2018-05-15 at 16 33 46" src="https://user-images.githubusercontent.com/17824796/40059821-c61332cc-585d-11e8-96c8-ea72d1d7c76b.png">
