### ISSUE TITLE
Animate dropdown

### ISSUE THREAD

**Issue by rmsutton** [ng-select/ng-select#645]
Not necessarily an issue but more of a question / feature request -- 

Is it possible to animate the drop down similar to how the date picker in Angular Material animates?

https://material.angular.io/components/datepicker/overview

**Comment by anjmao** [comment]
We could probably try using css transitions for animation.

**Comment by leifermendez** [comment]
You can try this

``` css
.ng-dropdown-panel {
  animation: growDown 100ms ease-in-out forwards;
  transform-origin: top center;
  border: 0 !important;
}
@keyframes growDown {
  0% {
    transform: scaleY(0)
  }
  80% {
    transform: scaleY(1.1)
  }
  100% {
    transform: scaleY(1)
  }
}
````
